### ISSUE TITLE
Cannot find module './vimhl'

### ISSUE THREAD

**Issue by daxiawj** [ppwwyyxx/hexo-tag-vimhighlight#3]
After upgrade to 0.1.6:

[error] HexoError: Plugin load failed: hexo-tag-vimhighlight
Error: Cannot find module './vimhl'

That's because of the absence of 'vimhl.js' ?!
